import type { Transaction } from './types';

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    date: new Date(2023, 9, 28).toISOString(),
    description: 'PAYMENT RECEIVED - CLIENT X',
    amount: 3500.0,
    type: 'income',
    category: 'Income',
  },
  {
    id: '2',
    date: new Date(2023, 10, 1).toISOString(),
    description: 'AMAZON WEB SERVICES',
    amount: 150.75,
    type: 'expense',
    category: 'Utilities',
  },
  {
    id: '3',
    date: new Date(2023, 10, 2).toISOString(),
    description: 'WHOLE FOODS MARKET',
    amount: 124.5,
    type: 'expense',
    category: 'Groceries',
  },
  {
    id: '4',
    date: new Date(2023, 10, 3).toISOString(),
    description: 'NETFLIX.COM',
    amount: 15.99,
    type: 'expense',
    category: 'Entertainment',
  },
  {
    id: '5',
    date: new Date(2023, 10, 5).toISOString(),
    description: 'STARBUCKS COFFEE',
    amount: 5.75,
    type: 'expense',
    category: 'Dining',
  },
  {
    id: '6',
    date: new Date(2023, 10, 5).toISOString(),
    description: 'SHELL GAS STATION',
    amount: 45.3,
    type: 'expense',
    category: 'Transport',
  },
  {
    id: '7',
    date: new Date(2023, 10, 7).toISOString(),
    description: 'ZARA ONLINE STORE',
    amount: 250.0,
    type: 'expense',
    category: 'Shopping',
  },
  {
    id: '8',
    date: new Date(2023, 10, 10).toISOString(),
    description: 'Transfer from Savings',
    amount: 500.0,
    type: 'income',
    category: 'Transfers',
  },
  {
    id: '9',
    date: new Date(2023, 10, 12).toISOString(),
    description: 'DR. JOHN SMITH - COPAY',
    amount: 25.0,
    type: 'expense',
    category: 'Uncategorized',
  },
  {
    id: '10',
    date: new Date(2023, 10, 15).toISOString(),
    description: 'PAYCHECK - ACME CORP',
    amount: 3500.0,
    type: 'income',
    category: 'Income',
  },
  {
    id: '11',
    date: new Date(2023, 10, 18).toISOString(),
    description: 'SQ *BLUE BOTTLE COFFEE',
    amount: 12.0,
    type: 'expense',
    category: 'Uncategorized',
  },
  {
    id: '12',
    date: new Date(2023, 10, 20).toISOString(),
    description: 'UBER TRIP',
    amount: 18.45,
    type: 'expense',
    category: 'Transport',
  },
  {
    id: '13',
    date: new Date(2023, 10, 22).toISOString(),
    description: 'COMCAST CABLE',
    amount: 85.0,
    type: 'expense',
    category: 'Utilities',
  },
  {
    id: '14',
    date: new Date(2023, 10, 25).toISOString(),
    description: 'APPLE.COM/BILL',
    amount: 9.99,
    type: 'expense',
    category: 'Uncategorized',
  },
];
